### ISSUE TITLE
Kebs spray-json can't resolve implicit for particular case class

### ISSUE THREAD

**Issue by dbronecki** [theiterators/kebs#11]
Following code:
```scala  
  test("issue") {
    import KebsProtocol._
    val jf = implicitly[JsonFormat[Request]]
  }
  case class Request(region: String, currency: String, date: String, code: String, items: List[RequestItem])
  case class RequestItem(itemCode: String, language: String, answers: Option[List[Answer]], requirements: String, travellers: String)
  case class Answer(answer: String)
```
Gives compilation error:
```
[error] diverging implicit expansion for type spray.json.JsonFormat[SprayValueEnumJsonFormatTests.this.Request]
[error] starting with macro method jsonValueEnumFormat in trait KebsEnumFormats
[error]     val jf = implicitly[JsonFormat[Request]]
```

**Comment by marcin-rzeznicki** [comment]
I'm not sure if there's much I can do about it. Probably the depth of implicit search is too big for the compiler. Eg. if you change `Option[List[Answer]]` to `List[Answer]` everything is fine. Another workaround is to define `implicit val requestFormat = jsonFormatN[Request]` manually.  It is also true that changing `Answer` by adding dummy field makes it compile - probably because only `RootJsonFormat` macro is being expanded in this case.

I do not have any idea how I could solve it. I'll leave this issue open for a while - in case someone might have better idea.

Thanks for reporting

**Comment by marcin-rzeznicki** [comment]
Looks like fb29526f4ab8dddf5781c6fb90cf3ca46b6747b7 magically fixed this issue. Closing 😄
