### ISSUE TITLE
Explicitly providing jsonFormatN yields different results than omitting it

### ISSUE THREAD

**Issue by farico** [theiterators/kebs#126]
I have this piece of code that converts case class to json:
```
import pl.iterators.kebs.json.KebsSpray
import spray.json._

object Kebsie extends DefaultJsonProtocol with KebsSpray {
  def main(args: Array[String]): Unit = {
    implicit val fmt = jsonFormatN[Chest]

    println(Chest(Seq("sword", "shield")).toJson.compactPrint)
    println(Chest2(Seq("sword", "shield")).toJson.compactPrint)
  }

  case class Chest(items: Seq[String])
  case class Chest2(items: Seq[String])
}
```

and expect both Chest and Chest2 to yield the same output:
`{"items":["sword","shield"]}`

however Chest2 json output is:
`["sword","shield"]`

**Comment by dbronecki** [comment]
This is expected behavior. Kebs flattens 1 element case classes by default. You can omit flattening by three different ways - please read https://github.com/theiterators/kebs#--kebs-eliminates-spray-json-induced-boilerplate-kebs-spray-json (paragraph starting with words "What if you do not want to use 'flat' format by default? You have three options to choose from:"). You used first option to tell Kebs that it shouldn't flatten `Chest` case class. `Chest2` however was left with defaults which is flat format.
