### ISSUE TITLE
kebs-spray-json: support scala 3

### ISSUE THREAD

**Issue by pjfanning** [theiterators/kebs#282]
* spray-json 1.3.6 supports Scala 3 - https://mvnrepository.com/artifact/io.spray/spray-json
* kebs-spray-json is not published for scala 3

I notice too that enumeratum support is vis Scala213for3 too but enumeratum now has a Scala3 release too.

**Comment by luksow** [comment]
Hi, there was no plan to support spray-json with Scala 3 as I thought it's not gonna be released but since it's there, I think it should be pretty straightforward to bring it in.

About enumeratum, well I wanted to only have support for proper Scala 3 enums everywhere... Do you think it's good to have that ported, so that the transition is smoother? We might prepare two different packages, one for both Scala 2.13/Scala 3 with enumeratum and one with plain enums only for Scala 3.

Last but not least, I want to stop supporting akka-http in favour of pekko-http, so maybe all these would be a good plan for 2.0.0, cleaning some older mess.

@pjfanning thoughts?

**Comment by pjfanning** [comment]
@luksow your plan seems ok to me.

I'm not a big user of kebs myself but the utilities it provides are very useful. I use kebs-spray-json in https://github.com/pjfanning/swagger-pekko-http-sample. That currently uses Scala 2.13 but I was considering using Scala 3.

**Comment by luksow** [comment]
@pjfanning this took a while but kebs 2.0.0 is released.

I took a stab at migrating swagger-pekko-http-sample to Scala 3, got it to compile but the request with swagger times out. Code is here: https://github.com/luksow/swagger-pekko-http-sample/commit/7f703c65bf724ab6bce4b57065ccaed05ab9aa35 

Not sure why.

**Comment by pjfanning** [comment]
Thanks @luksow - Your changes work fine when Scala 2.13 is used so I merged your changes but left the Scala version as is. I can confirm the hanging behaviour with Scala 3. I haven't worked out what is up yet but I'll continue to look into it. Thanks for the Kebs release and your research on the swagger sample.

**Comment by pjfanning** [comment]
I've done a little digging and the hang happens even if I remove all the swagger and kebs code. That is, the issue is reproducible with just the pekko code. I have stripped down the sample to just keep the hello endpoint. I'll raise this with the Pekko team. It seems to also happen with older versions of Pekko so that it doesn't appear to be a new issue.

**Comment by luksow** [comment]
@pjfanning Great, thanks for clarifying! That's also an interesting case study for Scala 2 -> 3 migration...
